# Generated by Django 2.2.2 on 2019-06-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtitle',
        ),
    ]
